version: 2
updates:
  # Enable version updates for npm  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5  # Reduced to be less overwhelming
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
    # Group updates to reduce noise - now that we're on modern versions
    groups:
      dev-tooling:
        patterns:
          - "prettier"
          - "eslint*"
          - "@eslint/*"
          - "lint-staged"
      testing:
        patterns:
          - "jest*"
          - "@playwright/test" 
          - "@types/jest"
      build-tools:
        patterns:
          - "rimraf"
          - "concurrently"
          - "web-ext"
          - "sharp"
      types:
        patterns:
          - "@types/*"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"  
      time: "06:00"
    open-pull-requests-limit: 3  # GitHub Actions updates are usually safe
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "github-actions"
      - "ci-cd"