blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/yourusername/settings-extension/tree/main/docs
    about: Check our comprehensive documentation for guides and references
  - name: 💬 Discussions
    url: https://github.com/yourusername/settings-extension/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🚀 Contributing Guide
    url: https://github.com/yourusername/settings-extension/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project