name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run unit tests
      run: npm test
      
    - name: Generate coverage report
      run: npm run test:coverage

  e2e-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        browser: [chromium, firefox]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extension
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps ${{ matrix.browser }}
      
    - name: Run E2E tests for ${{ matrix.browser }}
      run: npm run test:e2e -- --project=${{ matrix.browser }}

  performance-benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run performance benchmarks
      run: node test/ci/test-runner.js --benchmark
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v4
      with:
        name: performance-results
        path: test-results/
        if-no-files-found: warn

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Run dependency check
      run: npx better-npm-audit audit --level=moderate

  quality-gate:
    runs-on: ubuntu-latest
    needs: [test, e2e-tests, performance-benchmark]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code quality
      run: |
        npm run lint
        npm run format:check
        
    - name: Verify test coverage
      run: |
        npm run test:coverage
        node -e "
          const coverage = require('./coverage/coverage-summary.json');
          const thresholds = { lines: 80, functions: 80, branches: 80, statements: 80 };
          const total = coverage.total;
          
          let failed = false;
          Object.entries(thresholds).forEach(([metric, threshold]) => {
            if (total[metric].pct < threshold) {
              console.error(\`❌ \${metric} coverage \${total[metric].pct}% below threshold \${threshold}%\`);
              failed = true;
            } else {
              console.log(\`✅ \${metric} coverage \${total[metric].pct}% meets threshold \${threshold}%\`);
            }
          });
          
          if (failed) process.exit(1);
        "
        
    - name: Package extension
      run: npm run package
      
    - name: Upload extension artifacts
      uses: actions/upload-artifact@v4
      with:
        name: extension-packages
        path: web-ext-artifacts/