name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run unit tests
      run: npm test -- --selectProjects=unit
      
    - name: Run integration tests
      run: npm test -- --selectProjects=integration
      
    - name: Run performance tests
      run: npm test -- --selectProjects=performance
      
    - name: Generate coverage report
      run: npm run test:coverage
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  cross-browser-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build extension
      run: npm run build
      
    - name: Test Chrome extension
      run: npm run test:chrome
      
    - name: Test Firefox extension
      run: npm run test:firefox

  performance-benchmark:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run performance benchmarks
      run: node test/ci/test-runner.js --benchmark
      
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: performance-results
        path: performance-results.json

  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Run security audit
      run: npm audit --audit-level=moderate
      
    - name: Run dependency check
      run: npx better-npm-audit audit --level=moderate

  quality-gate:
    runs-on: ubuntu-latest
    needs: [test, cross-browser-test, performance-benchmark]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code quality
      run: |
        npm run lint
        npm run format:check
        
    - name: Verify test coverage
      run: |
        npm run test:coverage
        node -e "
          const coverage = require('./coverage/coverage-summary.json');
          const thresholds = { lines: 80, functions: 80, branches: 80, statements: 80 };
          const total = coverage.total;
          
          let failed = false;
          Object.entries(thresholds).forEach(([metric, threshold]) => {
            if (total[metric].pct < threshold) {
              console.error(\`❌ \${metric} coverage \${total[metric].pct}% below threshold \${threshold}%\`);
              failed = true;
            } else {
              console.log(\`✅ \${metric} coverage \${total[metric].pct}% meets threshold \${threshold}%\`);
            }
          });
          
          if (failed) process.exit(1);
        "
        
    - name: Package extension
      run: npm run package
      
    - name: Upload extension artifacts
      uses: actions/upload-artifact@v3
      with:
        name: extension-packages
        path: web-ext-artifacts/